name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: run
        run: make run
      - name: test
        run: make test

