name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: ls
        run: ls
      - name: run
        run: make run
      - name: test
        run: make test

  deploy-us-west-2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying us-west-2"

  deploy-us-east-1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying us-east-1"
